### ISSUE TITLE
Value Error in loss_f()

### ISSUE THREAD

**Issue by AsserAboElkhair** [PRBonn/bonnet#42]
This error occurs on some dataset not all of them:
I don't know why

`Weights for loss function (median frec/frec(c)):
 [0.07206047 0.98466394 1.3721456 ]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1628, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimensions must be equal, but are 1867776 and 1800000 for 'train_model/model/loss_0/loss/Pow' (op: 'Pow') with input shapes: [1867776,3], [1800000,3].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./cnn_train.py", line 186, in <module>
    net.train()
  File "/home/ubuntu/bonnet_run/bonnet/train_py/arch/abstract_net.py", line 1076, in train
    self.TRAIN["loss"], self.TRAIN["w_decay"])
  File "/home/ubuntu/bonnet_run/bonnet/train_py/arch/abstract_net.py", line 145, in loss_f
    focal_softmax = tf.pow(1 - softmax_mat, gamma_tf) * \
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/math_ops.py", line 444, in pow
    return gen_math_ops._pow(x, y, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 5293, in _pow
    "Pow", x=x, y=y, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1792, in __init__
    control_input_ops)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1631, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimensions must be equal, but are 1867776 and 1800000 for 'train_model/model/loss_0/loss/Pow' (op: 'Pow') with input shapes: [1867776,3], [1800000,3].`

**Comment by tano297** [comment]
Closing due to lack of activity. Reopen if it continues to be a problem
